### ISSUE TITLE
Cannot turn on/off or ajust the fan speed

### ISSUE THREAD

**Issue by Kathou99** [hunterjm/ac-infinity-hacs#5]
Hi, I don't know if it is normal but I can ajust the fan speed anf turn on/off.

Btw it's maybe a great idea to add the different mode like auto too?

Thank

There is the log:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/ac_infinity/fan.py:92
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 3 septembre 2023 à 23:58:49 (7 occurrences)
Last logged: 00:04:13

[140469960103488] A-Q1J1M - F4:22:12:82:1B:36: Failed to connect after 4 attempt(s): TimeoutError
[140472561698880] G-GR6DH - 34:85:18:5F:8B:32: Failed to connect after 4 attempt(s): TimeoutError
[140472561698880] A-Q1J1M - F4:22:12:82:1B:36: Failed to connect after 4 attempt(s): TimeoutError
[140472561698880] A-8EZ93 - FA:DB:54:C0:9A:EA: Failed to connect after 4 attempt(s): TimeoutError
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 204, in connect
    reply = await self._bus.call(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dbus_fast/aio/message_bus.py", line 370, in call
    await future
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/bleak_retry_connector/__init__.py", line 350, in establish_connection
    await client.connect(
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/wrappers.py", line 290, in connect
    connected = await super().connect(**kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bleak/__init__.py", line 531, in connect
    return await self._backend.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 141, in connect
    async with async_timeout(timeout):
  File "/usr/local/lib/python3.11/asyncio/timeouts.py", line 111, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 870, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 942, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/ac_infinity/fan.py", line 92, in async_turn_off
    await self._device.turn_off()
  File "/usr/local/lib/python3.11/site-packages/ac_infinity_ble/device.py", line 179, in turn_off
    await self._ensure_connected()
  File "/usr/local/lib/python3.11/site-packages/ac_infinity_ble/device.py", line 244, in _ensure_connected
    client = await establish_connection(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bleak_retry_connector/__init__.py", line 374, in establish_connection
    _raise_if_needed(name, device.address, exc)
  File "/usr/local/lib/python3.11/site-packages/bleak_retry_connector/__init__.py", line 314, in _raise_if_needed
    raise BleakNotFoundError(msg) from exc
bleak_retry_connector.BleakNotFoundError: A-Q1J1M - F4:22:12:82:1B:36: Failed to connect after 4 attempt(s): TimeoutError
```

**Comment by Kathou99** [comment]
Did is a features we will be able to make it work?
